### ISSUE TITLE
Segmentation error when parallelizing

### ISSUE THREAD

**Issue by urmagt** [hpparvi/ull_tp_2425#100]
I'm trying to parallelize the ex2.f90 file and I have to use the !$omp parallel / end parallel statements right before and after any part that has to run in parallel, or it throws a segmentation error. Any idea why this might be?

**Comment by evasola-alu** [comment]
Hi Urma, 
I'm not sure this will fix the issue, but have you tried using "omp single" to let the code know that the next block will need to be executed sequentially in a single thread? 
This is also good because it is more optimal to only open (& close) a parallel block once, so you should try to include the "single" block if you need to run something on one thread between parallel blocks. 
Hope it helps!

**Comment by urmagt** [comment]
That solved the issue, thanks!
